Dropdown menu
Habtamu210/portfoliopage pull request #8
Opened 2022-11-16 08:55 UTC by Habtamu210

Added JavaScript function for navigation bar

2022-11-16 09:11 UTC, leonardodiasb requested changes
# INVALID ❌ ❌ ❌ 

Hi @Habtamu210, 👋

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌
 - You added the eslintrc.json file correctly to your project but for the Github PR run the eslinter checks on your PR the linters.yml file in the .github/workflows/ folder needs to be updated too. Kindly update your linters.yml file following the instructions on [this page](https://github.com/microverseinc/linters-config/tree/master/html-css-js).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

✅ Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_⚠️ Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

----
_Invalid Code Review Request does not count into the code reviews limit._

2022-11-16 11:15 UTC, prolajumokeoni commented
Hi @Habtamu210 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have linters setup properly, This is the first project in which you should set up both [JavaScript](https://github.com/microverseinc/linters-config/tree/master/javascript) and [HTML&CSS](https://github.com/microverseinc/linters-config/tree/master/html-css) linters in the project repository.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-11-16 13:52 UTC, Abenezer-Tilahun reviewed
- [ ] Hello @Habtamu210 kindly check the comment

2022-11-16 13:59 UTC, Habtamu210 commented
@abenezer-tlahun.
How are you doing Abenezer? I can not fix this problem

(C:\Users\hp\Documents\portfoliopage\node_modules\stylelint\lib\utils\configurationError.js:10:14)

    at
C:\Users\hp\Documents\portfoliopage\node_modules\stylelint\lib\getConfigForFile.js:56:11
    at async Promise.all (index 0)

On Wed, Nov 16, 2022 at 5:52 AM Abenezer-Tilahun ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> Hi @Habtamu210 <https://github.com/Habtamu210>
>
> While you made a great effort in this project, unfortunately, I cannot
> proceed to review your code.
> Invalid Code Review Request
>
> You have submitted a project, that does not pass stylenit linters setup
> properly, Kindly check linters are green before the submit for review.
>
> Your Code Review Request will be marked as invalid in your Dashboard, so
> please submit a new one once you are ready 🙏
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification @abenezer-tlahun.
>
> Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Habtamu210/portfoliopage/pull/8#pullrequestreview-1182616752>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AISVLPYQ2A7PDRTCGP5KBQ3WITRJHANCNFSM6AAAAAASB67X4Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-11-16 17:39 UTC, Abenezer-Tilahun reviewed
Hi @Habtamu210

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
Invalid Code Review Request

### Invalid Code 
You have submitted a project, that does not pass stylenit linters setup properly, Kindly check linters are green before the submit for review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @abenezer-tlahun.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

2022-11-16 17:39 UTC, Abenezer-Tilahun commented on .stylelintrc.json
> -}
- [ ] Hello @Habtamu210 the reason is you removed configuration of .stylelintrc.json, Kindly add it again https://github.com/microverseinc/linters-config/blob/master/javascript/.stylelintrc.json

2022-11-16 23:31 UTC, Whoistolu requested changes
Hi @Habtamu210 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._
- [ ] [REQUIRED] I am recommending these changes here because we do not have it in the file changes. Kindly ensure that the About menu option takes a user to the About page. Presently, you have routed it to the Work page. Please fix this.
https://github.com/Habtamu210/portfoliopage/blob/89e31bab48a628bbf8bdf782f3d95a5d6672abac/index.html#L25

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

### N/A

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-16 23:31 UTC, Whoistolu commented on script.js
> +}));
- [ ] [REQUIRED] Kindly ensure that your design looks exactly like the design provided in template 2 of the figma. Let's stick to the properties e.g. font, colors, text, margins.
 ### Your Design
<img width="413" alt="Screenshot 2022-11-17 at 00 15 25" src="https://user-images.githubusercontent.com/58692590/202315473-e22dd90e-d0ad-4cc1-ab93-df5f62390385.png">

### Figma Design
<img width="381" alt="Screenshot 2022-11-17 at 00 17 33" src="https://user-images.githubusercontent.com/58692590/202315570-32593940-e9bb-41e2-8378-b7f711758bb6.png">

2022-11-17 06:29 UTC, Davidosky007 requested changes
Hi @Habtamu210 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
* No linter errors 👍 
* Professional looking PR 👍 
* Proper use of GitHub flow pattern 👍  

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidosky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-17 06:29 UTC, Davidosky007 commented on script.js
> +document.querySelectorAll('.nav-link').forEach((n) => n.addEventListener('click', () => {
* As mentioned by the previous reviewer your drop-down menu is still different from the given design Kindly work on it 🙏 
## Yours 
![image](https://user-images.githubusercontent.com/52497246/202372388-3e4abe14-0b0b-478f-8cce-a3c3dc9d9a8c.png)
## Figma design 
![image](https://user-images.githubusercontent.com/52497246/202372499-e0d92c51-72cb-4fb7-bd41-b3ee751d3926.png)

2022-11-17 10:38 UTC, Qoosim approved these changes
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @Habtamu210, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/f4e04d5e9518e3cbf972fb0f7611848a87ed4e1aa7770811bc22c5b957824887/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6c3253716972355a78666f5332374576532f67697068792e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-17 10:42 UTC, merged